Add missing `using System` in `AvaloniaHotReloadExtensions.cs`
Prevents a compilation error similar to:

```
packages\hotavalonia.extensions\2.0.0\contentFiles\cs\any\AvaloniaHotReloadExtensions.cs(179,66): error CS0246: The type or namespace name 'Func<,>' could not be found (are you missing a using directive or an assembly reference?)
```